# Generated by Django 5.1.3 on 2025-02-20 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('PatientID', models.CharField(max_length=50, unique=True)),
                ('P_National_ID', models.CharField(max_length=20, unique=True)),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Date_of_Birth', models.DateField()),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('Address', models.TextField()),
                ('Fhir_ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Phone_Number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('RecordID', models.AutoField(primary_key=True, serialize=False)),
                ('Diagnosis', models.TextField()),
                ('Treatment', models.TextField()),
                ('Date_Created', models.DateTimeField(auto_now_add=True)),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('AppointmentID', models.AutoField(primary_key=True, serialize=False)),
                ('Appointment_Date', models.DateTimeField()),
                ('Doctor_Name', models.CharField(max_length=100)),
                ('Notes', models.TextField(blank=True, null=True)),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patients.patient')),
            ],
        ),
    ]
