# Generated by Django 5.1.3 on 2025-02-20 22:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='last_arrived',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
