# Generated by Django 5.1.3 on 2025-02-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0004_alter_appointment_status_alter_patient_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
    ]
