# Generated by Django 5.1.3 on 2025-02-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0005_alter_patient_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='Status',
        ),
        migrations.AddField(
            model_name='appointment',
            name='Appointment_Status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Scheduled', 'Scheduled'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=10),
        ),
    ]
