# Generated by Django 5.1.7 on 2025-03-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0007_medicalrecord_abatement_medicalrecord_asserter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='Identifier_Type',
            field=models.CharField(choices=[('national', 'National ID'), ('hospital', 'Hospital ID'), ('insurance', 'Insurance ID')], default='hospital', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('unknown', 'Unknown')], max_length=10),
        ),
    ]
