# Generated by Django 5.1.7 on 2025-03-27 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0008_patient_email_patient_identifier_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='Email',
        ),
    ]
