# Generated by Django 5.1.7 on 2025-03-27 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0010_patient_emergency_contact_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practitioner',
            fields=[
                ('PractitionerID', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Phone', models.CharField(blank=True, max_length=15, null=True)),
                ('Specialization', models.CharField(blank=True, max_length=255, null=True)),
                ('License_Number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('Address', models.TextField(blank=True, null=True)),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('Updated_At', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='Allergies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='Medications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='Test_Results',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='Abatement',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='Evidence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='Onset',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='Subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='Patients.patient'),
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('EncounterID', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Notes', models.TextField(blank=True, null=True)),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patients.patient')),
            ],
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='Encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Patients.encounter'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='Recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Patients.practitioner'),
        ),
    ]
